apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello
        image: sejren/tp-kubernetes

